GET http://127.0.0.1:3000/api/produto/
###

GET http://127.0.0.1:3000/api/produto/1

###

POST  http://127.0.0.1:3000/api/produto
Content-Type: application/json

{
    "preco": 99,
    "nome": "Produto Teste ",
    "descricao": "nick Descriçã",   
    "desconto": 0,    
    "categoria": "Teste 3"
}

###

PATCH   http://127.0.0.1:3000/api/produto/2
Content-Type: application/json

{
    "nome": "Produto super novo 3"

}

###

DELETE http://127.0.0.1:3000/api/produto/2





